services:
  hugo:
    container_name: hugo
    # image: peaceiris/hugo:v0.131.0            # Minimum image
    image: peaceiris/hugo:v0.115.1-mod        # Hugo Modules
    # image: peaceiris/hugo:v0.120.0-full     # Hugo Modules and Node.js
    # image: ghcr.io/peaceiris/hugo:v0.x.x  # Docker images on GitHub Packages
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts